### ISSUE TITLE
Italy

### ISSUE THREAD

**Issue by Artpom** [stackTom/FSEarthTiles#25]
Hi, have done a big project 'Italy', and result is very disappointing.
Made some quick overfly over area of cities San Vincenzo and Rosignano Marittimo on western coast, and have noticed nasty anomalies which led me to remove whole Italy map.
Before removal been checking other areas and have similar issues.
Strange thing is that Google Earth which was used as map provider shows this area properly.
Any hint what may be the cause of that?

![italy1](https://github.com/stackTom/FSEarthTiles/assets/161880250/57b7f664-e29f-43a8-9630-4b40ef5fe764)

![italy2](https://github.com/stackTom/FSEarthTiles/assets/161880250/5534b33f-11fd-4a8d-9a49-2b31763c59a7)

![italy3](https://github.com/stackTom/FSEarthTiles/assets/161880250/a13a9eb9-124b-4705-9027-328397533729)

![italy4](https://github.com/stackTom/FSEarthTiles/assets/161880250/d518048c-eca8-4c44-9d7c-39b20f19c8bd)

Artur

**Comment by stackTom** [comment]
As you zoom in, there is sometimes a difference in the color of the imagery. Try it on Google maps. From a zoomed out state, it's all homogenous. But as you zoom in, coloring issues arise.

The solution is just to use a different provider. Sometimes Bing has better imagery for an area, sometimes Arc, etc. But it's not FSET's fault. As I said, zoom in Google maps in a web browser and you will see this issue :). It's just more apparent in the simulator because on Google, as you zoom in, you naturally see less imagery. Whereas the simulator will use these zoomed in images even when you are at altitude.

**Comment by stackTom** [comment]
Here's an example when you zoom in on Google:

![image](https://github.com/stackTom/FSEarthTiles/assets/13559181/c8e344d6-3470-401b-b969-03b55fa5d3bf)

Try with bing or Arc.

**Comment by Artpom** [comment]
Ok, actually i have started Italy again with Bing source - will see

**Comment by stackTom** [comment]
Let me know how it goes. It's best to use a web browser (or the built in map display in FSET) and zoom in before creating an area. This will let you select the best server for the area you want to make.

**Comment by Artpom** [comment]
Do you have any recommendations for specific areas ?

**Comment by stackTom** [comment]
Have a look here:

https://forum.thresholdx.net/public-pages/orthosourcelist/

Seems bing is pretty good for Italy. Ortho4xp sources work in FSET, just check the Providers folder.

**Comment by Artpom** [comment]
Very nice source - thanks a lot !
